name: Reusable Build and Deploy

on:
  workflow_call:
    inputs:
      python_version:
        required: false
        type: string
        default: "3.12"
      quarto_profile:
        required: false
        type: string
        default: "full"

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      setup_done: ${{ steps.set_output.outputs.setup_done }}
    steps:
      - name: Update apt
        run: sudo apt update

      - name: Install system packages
        run: sudo apt-get install -y librsvg2-bin libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version }}

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true
          version: 1.6.42

      - name: Mark setup complete
        id: set_output
        run: echo "setup_done=1" >> $GITHUB_OUTPUT

  render:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Render with Quarto
        uses: quarto-dev/quarto-actions/render@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          QUARTO_PROFILE: ${{ inputs.quarto_profile }}

  deploy:
    needs: render
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Commit rendered output
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "CI added changes $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"

      - name: Push changes to main branch
        uses: ad-m/github-push-action@master
        with:
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
